#ifndef __MAP_H__
#define __MAP_H__

// this header is used for map
#include "building.h"
#include "pos.h"
#include <array>
#include <iostream>
#include <random>
#include <vector>

#define SIDE_LENGTH 10
#define MAP_SIZE (2 * SIDE_LENGTH - 1)
#define PLAYER_0_BASE_CAMP_X 2
#define PLAYER_0_BASE_CAMP_Y (SIDE_LENGTH - 1)
#define PLAYER_1_BASE_CAMP_X (MAP_SIZE - 3)
#define PLAYER_1_BASE_CAMP_Y (SIDE_LENGTH - 1)
#define BLOCK_NUM (MAP_SIZE * (SIDE_LENGTH - 1) - SIDE_LENGTH)

// Pheromone scale: stored as int, real_value = pheromone_int / PHEROMONE_SCALE
constexpr int PHEROMONE_SCALE = 10000;
constexpr int LAMBDA_NUM = 97;   // 0.97 * 100
constexpr int LAMBDA_DENOM = 100;
constexpr int TAU_MIN_INT = 0;
constexpr int TAU_BASE_INT = 100000;  // 10.0 * PHEROMONE_SCALE

int distance(Pos a, Pos b);
// unsigned long long lcg();
template <typename T, std::size_t N, std::size_t... Args>
struct multi_dim_array {
    using type = std::array<typename multi_dim_array<T, Args...>::type, N>;
};

template <typename T, std::size_t N> struct multi_dim_array<T, N> {
    using type = std::array<T, N>;
};

template <typename T, std::size_t N, std::size_t... Args>
using multi_dim_array_t =
    typename multi_dim_array<T, N, Args...>::type; // Get your array type!

struct point {
    // 蚂蚁不可走区域
    bool valid = false;
    // 建塔区域
    int player = -1;
    // 
    DefenseTower *tower = nullptr;
    Headquarter *base_camp = nullptr;
    int pheromone[2];  // scaled by PHEROMONE_SCALE (10.0 -> 100000)
};


class Map {
  public:
    point map[MAP_SIZE][MAP_SIZE];
    Map();
    void init_pheromon(unsigned long long M);
    // NOTE: Here we have two versions of build/destroy.

    // Insert an object owned by Map
    // bool establish(int x, int y, int type, int player); // WARNING: This ID
    // is not compatible with the id given by Game! Insert only a reference
    void build(DefenseTower *);

    // Destroy an owned object by ID (this ID is generated by Map)
    bool destroy(int x, int y); //
    bool is_valid(int x, int y) const;
    int get_move(Ant *, Pos);
    void update_pheromone(Ant *ant);
    
    using Pheromone =
        multi_dim_array_t<double, 2, MAP_SIZE, MAP_SIZE>; // For JSON output
    Pheromone get_pheromone() {
        Pheromone p;
        for (int i = 0; i < MAP_SIZE; i++)
            for (int j = 0; j < MAP_SIZE; j++) {
                p[0][i][j] = (double)map[i][j].pheromone[0] / PHEROMONE_SCALE;
                p[1][i][j] = (double)map[i][j].pheromone[1] / PHEROMONE_SCALE;
            }
        return p;
    }
    void next_round();
    bool is_empty(int x, int y, int player) const;
};



#endif
